server:
  port: 8080
spring:
  application:
    name: system-notice-service

  config:
    import: optional:configserver:http://localhost:8888/

  cloud:
    config:
      profile: 

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
#
#system-notice:
#  level: "ERROR"
#  message: "Sistema esta com erro, volte daq umas horas"
#  default-value: "Usu√°rio"

  endpoint:
    health:
      show-details: ALWAYS